### ISSUE TITLE
`hash32` results differ from original farmhash

### ISSUE THREAD

**Issue by asilvas** [cjihrig/farmhash.wasm#1]
Results are not consistent with https://github.com/lovell/farmhash

Oddly hash64 (with or w/o seed) is consistent though.

As an extra bit of info tests shown a 2-4x slowdown over the above repo (*edit*: Which is to say not terrible so long as throughput isn't critical). Pretty interesting for wasm though.

**Comment by cjihrig** [comment]
@asilvas do you have any idea if this is a real bug, or a manifestation of [these comments](https://github.com/lovell/farmhash/blob/742f3fa9120dbf8a455813820cf0c7116770be19/src/upstream/farmhash.h#L88-L90) (keep in mind that in the context of those comments, wasm is a different "platform")?

**Comment by asilvas** [comment]
Not certain, but platform is unchanged as the underlying hardware and os is the same. Having consistent hashing is critical

**Comment by cjihrig** [comment]
> but platform is unchanged as the underlying hardware is the same

The comments that I referenced before are relevant here. The native module runs on your system platform. The wasm module runs on the wasm "platform" which can be different from your machine (for example, wasm endianness can be different your native endianness).

The only other thing I can think of is a bug in emscripten (which compiles the C++ to wasm). I'm inclined to believe that you're encountering "platform" differences, since the C++ code is exactly the same in this project as in the native module.

**Comment by asilvas** [comment]
You may very well be right in that this is an artifact of wasm or the compilation to wasm, but if endianness of the hardware isn't respected this is a pretty major flaw IMO. I'm fine if you want to close this, but wanted to make clear this is a pretty significant issue if hashes aren't going to be consistent across farmhash implementations.

**Comment by cjihrig** [comment]
> but if endianness of the hardware isn't respected this is a pretty major flaw IMO

I think you're misunderstanding. WebAssembly defines what the "hardware" looks like so that it can work the same across different browsers, operating systems, etc. See https://github.com/WebAssembly/design/blob/master/Portability.md

> this is a pretty significant issue if hashes aren't going to be consistent across farmhash implementations.

They already aren't consistent. The farmhash README states:

> The hash methods are platform dependent. Different CPU architectures, for example 32-bit vs 64-bit, Intel vs ARM, SSE4.2 vs AVX might produce different results for a given input.
